# Generated by Django 4.0.1 on 2022-10-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
