# Generated by Django 4.0.1 on 2022-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_car_booked_by_remove_car_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
