# Generated by Django 4.0.1 on 2022-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_customer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
