# Generated by Django 4.0.1 on 2022-11-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_customer_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cars',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
