# Generated by Django 4.0.1 on 2022-11-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_customer_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cars',
            field=models.IntegerField(default=0),
        ),
    ]
