# Generated by Django 4.0.1 on 2022-11-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_customer_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bookedby',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='bookcar',
            field=models.IntegerField(default=0),
        ),
    ]
